controller_manager:
  ros__parameters:
    update_rate: 500  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    robotiq_gripper_controller:
      type: position_controllers/GripperActionController
    robotiq_activation_controller:
      type: robotiq_controllers/RobotiqActivationController
    gripper_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

robotiq_gripper_controller:
  ros__parameters:
    default: true
    joint: robotiq_85_left_knuckle_joint

robotiq_activation_controller:
  ros__parameters:
    default: true

gripper_forward_position_controller:
  ros__parameters:
    joints:
      - robotiq_85_left_knuckle_joint
    interface_name: position